spring:
  application:
    name: minio-demo
  datasource:
    url: jdbc:postgresql://127.0.0.1/nostra_movie
    username: subrutin
    password: subrutin
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB
minio:
  url: http://localhost:9000
  access-key: avSNppr2rFVP3YbTz4vD
  access-secret: hLejLW1YecwNesTNPs1eKvYmLr4beTZHoJwCDpVi
app:
  provider: minio